### ISSUE TITLE
Problem with DomainAndFunctionDefinition

### ISSUE THREAD

**Issue by mastep84** [NeuroBox3D/VRL-NeuroBox-Plugin#24]
Defined functions are not recognized correctly by Diffusion and Buffer instances. Observation of odd blank and duplicate entries in dropdown menu. First occurance in bouton template project (neurobox-v01ff).

**Comment by bsumirak** [comment]
Hey, Martin.
This is an issue in the VRL-UserData plugin and has been fixed.
Loading your project should display several error notifications in the log saying
    <i>java.lang.NoSuchMethodException: <unbound>=UserDependentSubsetModel$FSDataType.setSelFctInd(intArray);</i>
You can ignore this. After saving the project they will not show up again.

Feel free to reopen the issue if the fix does not work for you.
