### ISSUE TITLE
Plugin resource path initialization does not work for console apps (NPE)

### ISSUE THREAD

**Issue by miho** [NeuroBox3D/VRL-NeuroBox-Plugin#25]
It seems that the resource path initialization is not done in the correct init method(). Running in console-app mode causes NPE in `ResourcePathProvider`.

**Comment by stephanmg** [comment]
I already investigated this for another VRL Plugin as a Console App.
I've code (CommonResourcePathProvider) which takes care of the correct initializing with exception handling. I may provide it for this plugin, if you desire. May be applicable to fix issue #27.

**Comment by bsumirak** [comment]
Hi, Michael -
resource path initialization is done in the plugin configurator's register() method.
If this is not correct, what is?

EDIT: Ah, sorry, I did not realize that this has already been fixed. Thanks!
